/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huaa_other_NativeDemo */

#ifndef _Included_com_huaa_other_NativeDemo
#define _Included_com_huaa_other_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huaa_other_NativeDemo
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_huaa_other_NativeDemo_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
